[package]
name = "rust_physics_engine"
version = "0.1.0"
authors = ["Brandon Ly <wowbob396@gmail.com>", "Jeron Lau <jeron.lau@plopgrizzly.com>"]

[dependencies]
adi_screen = { git = "https://github.com/PlopGrizzly/adi_screen.git" } # "^0.7"
aci_png = "^0.6"
