[package]
name = "rust_physics_engine"
version = "0.1.0"
authors = ["Brandon Ly <wowbob396@gmail.com>", "Jeron Lau <jeron.lau@plopgrizzly.com>"]

[dependencies]
adi_screen = "^0.6"
aci_png = "^0.5.2"
